In [1]:
##import the necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.preprocessing import StandardScaler

In [2]:
##load dataset into variable titled df (eventually change to Afolabi's studentencoded .csv file)

df = pd.read_csv("./student_scaled.csv")

In [5]:
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,1.023046,1.143856,1.360371,0.792251,-0.042286,-0.449944,0.062194,-0.236010,0.801479,-0.540699,...,True,False,True,False,False,False,True,True,False,False
1,0.238380,-1.600009,-1.399970,-0.643249,-0.042286,-0.449944,1.178860,-0.236010,-0.097908,-0.540699,...,False,False,False,True,False,False,False,True,True,False
2,-1.330954,-1.600009,-1.399970,-0.643249,-0.042286,3.589323,0.062194,-0.236010,-0.997295,0.583385,...,True,False,True,False,True,False,True,True,True,False
3,-1.330954,1.143856,-0.479857,-0.643249,1.150779,-0.449944,-1.054472,-1.238419,-0.997295,-0.540699,...,True,False,False,True,True,True,True,True,True,True
4,-0.546287,0.229234,0.440257,-0.643249,-0.042286,-0.449944,0.062194,-0.236010,-0.997295,-0.540699,...,False,False,False,True,True,False,True,True,False,False

In [9]:
##creating features variable to be used to in our unsupervised learning model

features = [
    "studytime",
    "freetime",
    "goout",
    "Dalc",
    "Walc",
    "health",
    "absences",
    "activities_yes"
]

X_features = df[features].copy()

X_features['activities_yes'] = X_features['activities_yes'].astype(int)
X_features.head()

,studytime,freetime,goout,Dalc,Walc,health,absences,activities_yes
0,-0.042286,-0.236010,0.801479,-0.540699,-1.003789,-0.399289,0.036424,0
1,-0.042286,-0.236010,-0.097908,-0.540699,-1.003789,-0.399289,-0.213796,0
2,-0.042286,-0.236010,-0.997295,0.583385,0.551100,-0.399289,0.536865,0
3,1.150779,-1.238419,-0.997295,-0.540699,-1.003789,1.041070,-0.464016,1
4,-0.042286,-0.236010,-0.997295,-0.540699,-0.226345,1.041070,-0.213796,0

In [27]:
## using the scaler feature to standardize the values of the columns in the features variable 
## (mothersed(Medu), fathersed (Fedu), and studytime (studytime) )
##this 

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)
df['cluster'] = kmeans.fit_predict(X_scaled)

In [29]:
df['cluster'].value_counts().sort_index()

cluster
0    163
1    104
2    128
Name: count, dtype: int64

In [30]:
df.groupby('cluster')[features].mean()

             Medu      Fedu  studytime
cluster
0        1.705521  1.558282   2.030675
1        3.509615  3.548077   2.663462
2        3.460938  2.914062   1.531250